# Configuration for probot/stale - https://github.com/probot/stale

daysUntilStale: 60
daysUntilClose: 14

exemptLabels:
  - pinned
  - security
  - safety
  - good first issue

staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 14 days if no further activity occurs.
  If this issue is still relevant, please comment or remove the stale label.

closeComment: >
  This issue was closed because it has been stale for 14 days with no activity.
  Feel free to reopen if this is still relevant.

limitPerRun: 30
