name: default
description: Conservative default safety policy for any ROS2 robot

velocity:
  linearMax: 0.5    # m/s
  angularMax: 1.5   # rad/s
  clampMode: false  # if true, reduce to max instead of blocking

acceleration:
  enabled: false           # enable to limit rate of velocity change
  linearMaxAccel: 1.0      # m/s² — max linear acceleration
  angularMaxAccel: 3.0     # rad/s² — max angular acceleration

geofence:
  xMin: -5.0
  xMax: 5.0
  yMin: -5.0
  yMax: 5.0
  zMin: 0.0
  zMax: 2.0

geofenceWarningMargin: 1.0  # meters — warn when approaching boundary

rateLimits:
  publishHz: 10          # max publishes per second
  servicePerMinute: 60   # max service calls per minute
  actionPerMinute: 30    # max action goals per minute

deadmanSwitch:
  enabled: false    # auto e-stop if no heartbeat received
  timeoutMs: 30000  # 30 second timeout

blockedTopics:
  - /rosout
  - /parameter_events

blockedServices:
  - /kill
  - /shutdown
